### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by ryaneford** [BrettMayson/Arma3Server#12]
`WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

Redirecting stderr to '/root/Steam/logs/stderr.txt'

[  0%] Checking for available updates...

[----] Verifying installation...

Steam Console Client (c) Valve Corporation

-- type 'quit' to exit --

Loading Steam API...OK.

Logging in user 'A3SERVERDUMMY' to Steam Public ...


Logged in OK

Waiting for user info...OK

 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)

Error! App '233780' state is 0x202 after update job.

Traceback (most recent call last):

  File "/launch.py", line 30, in <module>

    launch = "./arma3server -mod={} -world={}".format(mods('mods'), os.environ["ARMA_WORLD"])

  File "/launch.py", line 18, in mods

    mods = [os.path.join(d,o) for o in os.listdir(d) if os.path.isdir(os.path.join(d,o))]

FileNotFoundError: [Errno 2] No such file or directory: 'mods'`

**Comment by Dahlgren** [comment]
You "need" to mount a volume at `/arma3/mods` which can either be empty or contain mods
