### ISSUE TITLE
Docker image is not up to date with repository

### ISSUE THREAD

**Issue by matteprl** [BrettMayson/Arma3Server#17]
Hi

I wanted to switch to x64 server binary, and I noticed that the image in docker repo is older than repository. Quick investigation confirmed - launch.py inside image doesn't use `ARMA_BINARY` env. That means that features like branch selection also won't work out of the box.

Please fix :)

**Comment by BrettMayson** [comment]
This was caused by my changing my github name, thanks for the heads up
