### ISSUE TITLE
Docker doesn't appear to be launching headless clients

### ISSUE THREAD

**Issue by Sylvaeseel** [BrettMayson/Arma3Server#18]
When launching with headless clients env at anything other than 0, they don't seem to launch with the server in the output. Is there something special you need to do after changing the env variable?

**Comment by BrettMayson** [comment]
Can you provide more information about your config? The latest version was working for me this past weekend

**Comment by Sylvaeseel** [comment]
![git1](https://user-images.githubusercontent.com/3047592/110724477-db325400-81e3-11eb-9f61-f2c4dbbaa07a.PNG)
 if you meant something else, just let me know but that's how I have it set up

**Comment by BrettMayson** [comment]
Des your mission have headless client slots?

**Comment by Sylvaeseel** [comment]
Yes, 3 of them, I'm using KP_Liberation Tanoa, come to think of it though, I haven't checked if the HC slots are setup correctly

**Comment by Sylvaeseel** [comment]
They are indeed setup correctly

**Comment by bashbers** [comment]
I've just added a headless_client to my kp_liberation.Altis server and it works perfectly fine. See:
![image](https://user-images.githubusercontent.com/23037527/120119579-cccb5700-c198-11eb-8b73-74c55a5f25bb.png)

**Comment by Sirata89** [comment]
> ![git1](https://user-images.githubusercontent.com/3047592/110724477-db325400-81e3-11eb-9f61-f2c4dbbaa07a.PNG) if you meant something else, just let me know but that's how I have it set up

Which host is this through?

**Comment by Sylvaeseel** [comment]
It was hosted on my own personal server, but as this was nearly a year ago and was never resolved, I ended up moving to a different image, sorry
