### ISSUE TITLE
Workshop mods

### ISSUE THREAD

**Issue by bashbers** [BrettMayson/Arma3Server#21]
What's a sustainable way of managing workshop mods?
Currently I need to do a lot of manual labor in order to load 1 file eg.
1. download from steam locally
2. convert to local mod
3. upload using filezilla to servermods / mods

**Comment by BrettMayson** [comment]
I can add workshop support in a few days, or PRs are welcome

**Comment by bashbers** [comment]
That would be great! Looking forward to the PR! :)

**Comment by bashbers** [comment]
I've looked more into this issue and it appears that the logged in steamcmd user needs to own a copy of Arma 3. Maybe we could work something out to use a third-party workshop downloader like:
https://steamworkshopdownloader.io/

If not, then we should document very clearly that the connected user should own Arma 3 in its library, and that it can't be the same as your personal account for two reasons:

Steamcmd logged in counts as a logged-in session, effectively blocking you from using your personal account.
For security reasons it is recommended that you create a new Steam account just for your dedicated servers

Also stumbled upon this python script which could be of use:
https://gist.github.com/Freddo3000/a5cd0494f649db75e43611122c9c3f15
