### ISSUE TITLE
Trying to setup this docking container with server setttings?

### ISSUE THREAD

**Issue by jonneymendoza** [BrettMayson/Arma3Server#33]
Hi, i am quite new to all of on docker and just installed both docker and docker container.

i did the following steps to try and get this docker image to run

1. docker pull synixebrett/arma3server 

2. ```sudo docker create \
        --name=arma-server \
        -p 2302:2302/udp \
        -p 2303:2303/udp \
        -p 2304:2304/udp \
        -p 2305:2305/udp \
        -p 2306:2306/udp \
        -v /docker/arma3/missions:/arma3/mpmissions \
        -v /docker/arma3/configs:/arma3/configs \
        -v /docker/arma3/mods:/arma3/mods \
        -v /docker/arma3/servermods:/arma3/servermods \
        -e ARMA_CONFIG=main.cfg \
        -e STEAM_USER=myUserName\
        -e STEAM_PASSWORD=mypaswordN \
        synixebrett/arma3server```

How do i actually setup the servers name and password and admin passwords?

**Comment by BrettMayson** [comment]
It will create `main.cfg` inside of /docker/arma3/configs, you can then edit that file and restart the container

**Comment by jonneymendoza** [comment]
> It will create `main.cfg` inside of /docker/arma3/configs, you can then edit that file and restart the container

It does. all i see in that path is another folder called profiles which has DataCache, home and mpstatistcs_113.log files

**Comment by BrettMayson** [comment]
You can create one there then, using https://community.bistudio.com/wiki/Arma_3:_Server_Config_File
