### ISSUE TITLE
Server wont load Creator DLC

### ISSUE THREAD

**Issue by Peer202** [BrettMayson/Arma3Server#36]
I cant seem to get the server to load a creatordlc. When starting the server by using `Docker-compose up` the server does start but the Creator DLC is listed as "not found " in the Log. And no missions using the creator DLC are available.

[Arma_Server_log.txt](https://github.com/BrettMayson/Arma3Server/files/7572323/Arma_Server_log.txt)

This is my .env file. Ive changed the password obviously.
> ARMA_BINARY=./arma3server_x64
> ARMA_CONFIG=main.cfg
> ARMA_LIMITFPS=100
> ARMA_PROFILE=main
> ARMA_WORLD=empty
> HEADLESS_CLIENTS=0
> MODS_LOCAL=true
> PORT=2302
> STEAM_BRANCH=creatordlc
> STEAM_PASSWORD=password
> STEAM_USER=user
> ARMA_CDLC="gm"
 the same thing happens if i set ARMA_CDLC=gm
 
The starting parameters for the arma3server is (grabbed from the docker log) : 
 LAUNCHING ARMA SERVER WITH ./arma3server_x64 -limitFPS=100 -world=empty   -mod="gm"  -config="/arma3/configs/main.cfg" -port=2302 -name="main" -profiles="/arma3/configs/profiles" -serverMod="" 
 
 Im certain this is just me being dumb, but i dont know what to try next.

**Comment by BrettMayson** [comment]
Can you try `ARMA_CDLC="GM"`. I have a feeling that's the issue

**Comment by Peer202** [comment]
Unfortunatly the same thing happens just with a capitalizes GM.

**Comment by Peer202** [comment]
I think the Issue might be that the Arma Server is started with the `-mod="gm"` argument while at least the client version needs to be started with the `-mod=gm`  so without the quotationmarks.

**Comment by BrettMayson** [comment]
Are you able to test that? You'd need to edit the python files then start the container again

**Comment by Peer202** [comment]
I did not manage to modify your Docker Image, but i was able to confirm that the Solution is that cdlcs need to be loaded using the `-mod=gm` parameter for example. I opened a console in the docker container and manually launched a new server process with the following parameters which started and detected the gm cdlc just fine;
 `./arma3server_x64 -limitFPS=100 -world=empty   -mod=gm  -config="/arma3/configs/main.cfg" -port=3302 -name="main" -profiles="/arma3/configs/profiles" -serverMod=""`

**Comment by Peer202** [comment]
https://github.com/Peer202/Arma3Server/commit/71cfdba5860b671a4bec8b1989f25b9051b23758
This would be my attempt to fix the issue. Because i dont know how to modify the docker image, im not sure how to test this. :/

**Comment by Peer202** [comment]
@BrettMayson Thank you for the change, the server now loads the CDLC just fine.
