### ISSUE TITLE
force_install_dir needs to be set before the +login parameter in steamcmd

### ISSUE THREAD

**Issue by juliangiebel** [BrettMayson/Arma3Server#42]
I got this error: `Please use force_install_dir before logon!`

After ensuring that force_install_dir is always passed before +login this error stopped showing up.

**Comment by trailingslash** [comment]
How did you ensure that force_install_dir is always passed before +login?

**Comment by tklein1801** [comment]
How did u even pass the Steam login? I fail bcause I can't enter my auth-code

**Comment by juliangiebel** [comment]
I used an account I dissabled steam guard on.
Maybe this would work with steam guard? https://steamcommunity.com/dev/managegameservers
*Sorry for the late reply. I missed the notification.*
