### ISSUE TITLE
Keys not copying when folder has different name

### ISSUE THREAD

**Issue by Sanderth** [BrettMayson/Arma3Server#57]
This is my first public GitHub issue, excuse me if this is not how it works. Didn't know if there's a better way I could let this be known :)

I noticed that when a certain mod has a **key** folder (so not the plural form **keys**), they won't be copied. This can be attributed to how the python script(s) behave.

I suggest either including this in the readme, or updating the python script(s) responsible to including both a plural and single form of the word **key**.

Thanks! :)

**Comment by BrettMayson** [comment]
The mods should be using keys, but I don't see any harm in adding both anyway

**Comment by Sanderth** [comment]
Great! Thanks for the effort :)

**Comment by BrettMayson** [comment]
https://github.com/BrettMayson/Arma3Server/blob/master/keys.py#L7

Actually it already doesn't matter, make sure you are using the latest release
