### ISSUE TITLE
Dockerhub image outdated

### ISSUE THREAD

**Issue by stuffinator** [BrettMayson/Arma3Server#61]
The Dockerhub images was updated 2 years ago. All the pull requests after that are not included.

Are there any plans to update it at some point?

**Comment by jonpas** [comment]
Images are uploaded to GitHub registry now: https://github.com/BrettMayson/Arma3Server/pkgs/container/Arma3Server%2Farma3server

Docker Hub one should probably just be deleted @BrettMayson?
