### ISSUE TITLE
Steam Initialization Failed

### ISSUE THREAD

**Issue by jschmidt92** [BrettMayson/Arma3Server#64]
I'm getting a steam initialization failed when the server launches which in return causes the server to not show up in the server browser and not allowing direct connect to work.
[armadockerserver.log](https://github.com/BrettMayson/Arma3Server/files/11713260/armadockerserver.log)

**Comment by BrettMayson** [comment]
> 2023-06-10 14:47:30 CallExtension 'ArmaRedisClient' could not be found
> 2023-06-10 14:47:30 19:47:30 ArmaRedisClient: DLL Version  found

This may be windows only, or perhaps you need to run with 64bit Linux server

There is also a lot of configs errors coming from the `ec` assets. In either case, I don't think this is directly related to anything that this docker image does

**Comment by jschmidt92** [comment]
I just tried running the docker image using docker compose with a fresh repo pull no edits and the same error. Here's the error log:
[arma3server.log](https://github.com/BrettMayson/Arma3Server/files/11713486/arma3server.log)

**Comment by jschmidt92** [comment]
I removed the network_mode: host param in the docker-compose.yml and the game server is now showing up in the server browser.
