### ISSUE TITLE
Ideas For More Easily Accessible Server File Management?

### ISSUE THREAD

**Issue by lawayne** [BrettMayson/Arma3Server#75]
Hey there,

Let me preface my question by saying that I'm fairly new to this homelabbing/sysadmin stuff and have just been doing it as a hobby on the side, so I acknowledge that my setup is probably far from ideal and I'm happy to hear anyone's thoughts on how I could change or improve. Ideally I'd like to hear some ideas that don't involve a complete refactor of my entire set up as that's exactly what I've just gone through for the past few months, but if that's somehow the corner I've painted myself into, then so be it.

Aside from that though, I'm currently running this image via docker within a Linux container hosted by Proxmox. I've done a fair bit of tinkering to try and essentially force the Steamcmd and Arma 3 installations to use SMB shares in order to make the files more easily accessible from outside of the terminal, however, it just doesn't seem to want to work. Steamcmd will refuse to download files into my SMB shares no matter how I try to adjust the permissions, and if I try instead to install Arma 3 outside of the SMB share, then move the installation, the files just won't appear in the SMB share and will be installed elsewhere, in an unknown location and not inside the /root/arma3 directory.

As of right now, my server's files are only accessible through either the LXC terminal or through a Portainer terminal. I'm running my Arma 3 server through this LXC/docker/container setup because from what I could tell based on research, it just seemed to be the most cost efficient option with my currently limited resources (I am also using Proxmox to host other services, so my resources are being spread across other VMs and it's not _currently_ in my budget to upgrade). While I can certainly make do with terminal commands, I'd much prefer a more accessible and user-friendly method, like simply using my Windows file explorer from my personal desktop (the original plan, which failed. See previous paragraph). What would be the simplest way to gain access to my server's files through some sort of GUI so that they could be more easily managed?

**Comment by BrettMayson** [comment]
Are you mounting a SMB share from another machine or NAS and trying to run Arma on it? That's going to absolutely be a very bad time.

You could mount the paths to a volume, and serve SMB from the same machine that is running docker, you couild also look at something like https://github.com/filebrowser/filebrowser

**Comment by lawayne** [comment]
Yes, that was the plan, although upon reading it back to me it does seem very obviously like a bad idea. I'm also looking into the Docker Explorer extension for VS Code,

Technically the SMB share comes from the same physical machine, however, it is a separate virtual machine. As nice as it would be to have a dedicated machine to use as a NAS, it's just not in the budget right now.

**Comment by BrettMayson** [comment]
> however, it is a separate virtual machine

That's still going to be an absolutely horrible time, SMB can manage for applications that just serve large files over time, like a media server, but Arma needs faster random access to files that SMB is not going to be able to provide it with

**Comment by lawayne** [comment]
Indeed, I've resolved to simply stick with my non-NAS storage, I already planned to expand it eventually anyway.

Evidently my googling was insufficient when I originally made this post, I've found a number of other methods to manage files on docker containers along with what you suggested, not sure what was wrong with my original search query, but thanks anyway for your assistance and for the work you put into this image!
